Add Benchmarks for metrics
swift-server/swift-prometheus pull request #106
Opened 2023-10-13 11:14 UTC by freef4ll

# Motivation

Adding benchmark tests in order to aid development and avoid performance regressions.

Benchmark is added in the same fashion as for  [swift-nio](https://github.com/apple/swift-nio/pull/2536) and [swift-certifcates](https://github.com/apple/swift-certificates/pull/125).

# Modifications

Benchmarks are added for incrementing a counter, gauge,  histogram and an export of 5000 metrics from the esystem.

# How to execute benchmark
```
cd Benchmarks
swift package benchmark
```
In Xcode can open the project like and use Instruments to profile:
```
open --env BENCHMARK_DISABLE_JEMALLOC=true Package.swift
```

# Result

Benchmarks are available, and performance difference between v1 is great which only managed to increment 2-3k times per second.

2023-10-13 12:01 UTC, FranzBusch requested changes
Thanks for opening this up. Super useful!

There are a few things different to the certificate and nio setup that we should change:
1. Update the docker files to also run the benchmarks
2. For now only collect total allocation metrics
3. Provide a similar script to update all benchmark thresholds locally
4. Split the benchmark code into the benchmark definition and separate files for the benchmarks under test. NIO and certificates do the same.
5. Add documentation to the README how to run those.

2023-10-13 12:01 UTC, FranzBusch commented on Benchmarks/Package.resolved
This file should be gitignored.

2023-10-25 10:13 UTC, FranzBusch commented on Benchmarks/Benchmarks/PrometheusBenchmarks/Benchmarks.swift
> +    // Benchmark.defaultConfiguration.metrics = [.wallClock, .throughput, .mallocCountTotal]
Can we remove this?

2023-10-25 10:13 UTC, FranzBusch commented on Benchmarks/Benchmarks/PrometheusBenchmarks/Benchmarks.swift
> +    Benchmark("Counter #2") { benchmark, run in
Can we give them slightly better names than 1 and 2?

2023-10-25 10:13 UTC, FranzBusch commented on Benchmarks/Benchmarks/PrometheusBenchmarks/DurationHistogram.swift
> +    let histogram = registry.makeDurationHistogram(name: "histogram_1", labels: makeLabels(3),
Can we use a different line break formatting here and break before `name`, `labels` and ` buckets`?

2023-10-25 10:13 UTC, FranzBusch commented on Benchmarks/Package.resolved
The file is still here

2023-10-26 12:23 UTC, FranzBusch commented
@swift-server-bot add to allowlist

2023-10-26 12:24 UTC, FranzBusch commented
@swift-server-bot test this please

2023-10-31 17:32 UTC, FranzBusch approved these changes
LGTM from my side! @fabianfett you mind giving this a look?

2024-02-23 10:45 UTC, hassila commented
Anything we can do to help move this forward?

2024-02-26 04:02 UTC, ktoso commented
From my perspective this looks fine, any concerns @FranzBusch @fabianfett ?

2024-02-26 04:02 UTC, ktoso approved these changes

2024-02-28 06:55 UTC, ktoso commented
@swift-server-bot test this please

2024-02-28 07:10 UTC, ktoso commented
Failures because of missing baseline: `Could not find any matching absolute thresholds at path [Thresholds/swift-5.7.3-RELEASE/], failing threshold check.`


@fabianfett I think had some opinions before we merged here?

2025-06-06 16:50 UTC, freef4ll commented
@FranzBusch , maybe time to finally merge?

It looks like how the thresholds are updated has changed; which project should be used as a baseline? [swift-certifcates](https://github.com/apple/swift-certificates/tree/main/dev) or https://github.com/apple/swift-nio/pull/3258 ?

2025-06-18 15:21 UTC, freef4ll commented
@rnro - could you clarify on how the thresholds should be updated and maintained now? For example https://github.com/apple/swift-distributed-tracing/pull/171 has no script nor docker images

2025-06-19 07:23 UTC, rnro commented
> @rnro - could you clarify on how the thresholds should be updated and maintained now? For example [apple/swift-distributed-tracing#171](https://github.com/apple/swift-distributed-tracing/pull/171) has no script nor docker images

Hi! The common path we are currently using is tied to the fact that the primary use case of the benchmarks is as part of CI, which doesn't seem to apply here. 

Most repositories are now running their benchmarks in GitHub Actions using the reusable workflow from NIO https://github.com/apple/swift-nio/blob/main/.github/workflows/pull_request.yml#L25-L30 . In that case matching the running environment of CI closely is our aim so that we don't get spurious failures blocking PRs. That workflow will output a git diff in the even that it discovers a discrepancy which can then locally be applied and committed.

If for whatever reason these benchmarks aren't part of GitHub Actions CI then we'll have to use the old method or an alternative one.

2025-06-19 14:55 UTC, freef4ll commented
Thanks @rnro, I have added the benchmark run into PR workflow.

2025-06-23 09:19 UTC, rnro commented on .github/workflows/pull_request.yml
> +    # Workaround https://github.com/nektos/act/issues/1875
```suggestion
```
Tiny nit: this is only needed in the NIO repo itself (but has accidentally been spread around), it relates to how we are using a full repo reference to a workflow which is local to NIO to workaround an issue.

2025-08-13 06:34 UTC, freef4ll commented on .github/workflows/pull_request.yml
> +    # Workaround https://github.com/nektos/act/issues/1875
Sure, removed!

2025-08-26 04:25 UTC, ktoso commented
Lemme try to push this over the finish line

2025-08-26 05:44 UTC, ktoso commented
Pushed this over the finish line over here; we can merge as a merge commit to keep attribution -- thank you for your work on this @freef4ll !

2025-08-26 05:45 UTC, closed without merging